<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2fc23c0c-5012-4e56-8ec8-3c90fe085a70</testSuiteGuid>
   <testCaseLink>
      <guid>5c431e8c-5536-4cf9-8b18-c11162a81581</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>63d1c535-5e64-46a4-8d1e-0521f23b3a29</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginDetails</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>63d1c535-5e64-46a4-8d1e-0521f23b3a29</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>4da5a2a3-eda8-44f5-9802-575ae9da2b3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>63d1c535-5e64-46a4-8d1e-0521f23b3a29</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f6881c53-b8ff-4582-8784-c60cabf5eb57</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98a08f8f-6ac7-45ef-9506-f705caf88d83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6abaf5ef-48d7-4b65-a068-e297e8d8f1c6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/InternalData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6abaf5ef-48d7-4b65-a068-e297e8d8f1c6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>4da5a2a3-eda8-44f5-9802-575ae9da2b3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6abaf5ef-48d7-4b65-a068-e297e8d8f1c6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f6881c53-b8ff-4582-8784-c60cabf5eb57</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
